### ISSUE TITLE
Stuck calculations in the new daemon

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida_core#1335]
This is a continuation of #1274. 

Observed behaviour: Even after the fix in PR #1304, calculations still sometimes get stuck (especially long-running ones) after the daemon was restarted.

Apart from the general "it doesn't work", I also have a reproducible error:
- Submit a calculation, preferably over SSH. I'm not sure if this is essential, but it makes the timing easier.
- Stop the calculation.
- Exactly when it is marked as ``DONE`` in ``verdi calculation list``, but before it is retrieved / finished, try stopping the daemon
- The daemon now hangs indefinitely, and can only be ``kill -9``ed. The last log (on ``INFO`` loglevel) is "Querying the workflow DB".
- The calculation is now stuck in ``DONE``.

in order to more generally improve the stability of the daemon w.r.t. stuck calculations, maybe we should add a sort of "cleanup" task, that picks up calculations which are still in a valid non-finished state, but don't have a task associated with them?

**Comment by greschd** [comment]
Maybe related: I managed to get the following exception

```
ERROR:tornado.application:Exception in callback <bound method PendingTask._on_task_done of <kiwipy.rmq.tasks.PendingTask object at 0x7f00e9900850>> for <plumpy.persistence.SavableFuture object at 0x7f00e9946610>
Traceback (most recent call last):
  File "/home/greschd/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/tornado/concurrent.py", line 325, in _set_done
    cb(self)
  File "/home/greschd/.virtualenvs/aiida_dev/src/kiwipy/kiwipy/rmq/tasks.py", line 69, in _on_task_done
    response)
  File "/home/greschd/.virtualenvs/aiida_dev/src/kiwipy/kiwipy/rmq/tasks.py", line 186, in _task_finished
    self._channel.basic_ack(delivery_tag=delivery_tag)
  File "/home/greschd/.virtualenvs/aiida_dev/local/lib/python2.7/site-packages/pika/channel.py", line 199, in basic_ack
    raise exceptions.ChannelClosed()
ChannelClosed
```

by trying the same procedure as above, but with direct transport. Since retrieving / finishing the calculation is almost instantaneous, the calculation _did_ finish correctly (from what I can tell) before the daemon shut down, and the error only appeared upon restarting the daemon.

**Comment by greschd** [comment]
I used the following dummy calculation for my tests: https://github.com/greschd/aiida-wait

**Comment by sphuber** [comment]
I have quite a few fixes related to daemon restarting and or stopping of workers in [this open PR](https://github.com/aiidateam/aiida_core/pull/1333). It is just waiting for a small fix in `kiwipy` to be pushed by @muhrin . When that is done and we merge it, it would be good if you can retry your experiment to see if it persists.

**Comment by greschd** [comment]
Awesome, I guess I should review that PR then :slightly_smiling_face:

**Comment by greschd** [comment]
What's your take on implementing a "cleanup" task? In principle it shouldn't be needed if everything is done right, but since potentially a lot of compute time is wasted when a calculation is just stuck, maybe there should still be a way to "rescue" it?

**Comment by sphuber** [comment]
Given the situation that a process seems stuck because the task got lost for whatever reason, I have been doing the following:

```
from aiida.work.persistence import AiiDAPersister

persister = AiiDAPersister()
bundle = persister.load_checkpoint(<pk>)
process = bundle.unbundle()
process.execute()
```
You can inspect the `bundle` to see if everything looks ok, and if it was not progressing simply because the task got lost, calling `execute` on the recreated `process` instance should start ticking it again. Like you said, in principle this shouldn't happen, so I would like to wait with officially adding an endpoint to do something like this. If after a lot of testing we still see this happening, we can see if can add some recovery mode

**Comment by greschd** [comment]
Hmm, that worked for the simple test calculation, but for the real ones I'm getting 

```
<ipython-input-5-a6a905855a48> in <module>()
----> 1 b.unbundle()

/home/greschd/.virtualenvs/aiida_tbextraction_workflows/src/plumpy/plumpy/persistence.pyc in unbundle(self, load_context)
     66             load_context.copyextend(class_loader=utils.load_object(class_loader_name))
     67 
---> 68         return Savable.load(self, load_context)
     69 
     70 

/home/greschd/.virtualenvs/aiida_tbextraction_workflows/src/plumpy/plumpy/persistence.pyc in load(saved_state, load_context)
    411         try:
    412             class_name = Savable._get_class_name(saved_state)
--> 413             load_cls = load_context.class_loader.load_class(class_name)
    414         except KeyError:
    415             raise ValueError("Class name not found in saved state")

/home/greschd/.virtualenvs/aiida_tbextraction_workflows/src/plumpy/plumpy/class_loader.pyc in load_class(self, identifier)
     32                 return obj_class
     33 
---> 34         return self.find_class(identifier)
     35 
     36     def class_identifier(self, obj):

/home/greschd/.virtualenvs/aiida_tbextraction_workflows/src/plumpy/plumpy/class_loader.pyc in find_class(cls, identifier)
     16         Load a class from a string
     17         """
---> 18         return utils.load_object(identifier)
     19 
     20     def load_class(self, identifier):

/home/greschd/.virtualenvs/aiida_tbextraction_workflows/src/plumpy/plumpy/utils.pyc in load_object(fullname)
    256             obj = getattr(obj, name)
    257         except AttributeError:
--> 258             raise ValueError("Could not load object corresponding to '{}'".format(fullname))
    259 
    260     return obj

ValueError: Could not load object corresponding to 'abc.JobProcess_aiida_vasp.calcs.vasp.VaspCalculation'
```

Somehow the class name in the bundle seems to be messed up, but manually changing it to ``aiida_vasp.calcs.vasp.VaspCalculation`` just gives another error: 

```
In [8]: b['!!meta']['class_name'] = 'aiida_vasp.calcs.vasp.VaspCalculation'

In [9]: b.unbundle()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-a6a905855a48> in <module>()
----> 1 b.unbundle()

/home/greschd/.virtualenvs/aiida_tbextraction_workflows/src/plumpy/plumpy/persistence.pyc in unbundle(self, load_context)
     66             load_context.copyextend(class_loader=utils.load_object(class_loader_name))
     67 
---> 68         return Savable.load(self, load_context)
     69 
     70 

/home/greschd/.virtualenvs/aiida_tbextraction_workflows/src/plumpy/plumpy/persistence.pyc in load(saved_state, load_context)
    415             raise ValueError("Class name not found in saved state")
    416         else:
--> 417             return load_cls.recreate_from(saved_state, load_context)
    418 
    419     @classmethod

AttributeError: type object 'VaspCalculation' has no attribute 'recreate_from'
```

Any idea why that might be? The ``VaspCalculation`` does have a custom metaclass (not quite sure what that's doing), in case that might be important.

**Comment by greschd** [comment]
I'm suspecting this was also the root issue as to why these calculations never got picked up again...

**Comment by sphuber** [comment]
Yes that's exactly the issue, for some unknown reason, the bundle did not get the correct class loader and so when plum tried to load it, it fails as it does not recognize aiidas jobprocess class. Again, hopefully this is fixed by the other PR, so it would be good to test your examples with that fix

**Comment by greschd** [comment]
Ah cool, I'll do that then.

I agree on not making the "reviving" a public endpoint. If it becomes too painful for us we can make it a ``devel`` command, but ideally we want to know about it whenever there's an issue that actually triggers people to use that.

**Comment by greschd** [comment]
Here's the last ``DEBUG`` level message before the daemon gets stuck using the process described in my first comment:

```
03/27/2018 09:21:31 PM <9441> aiida.transport.SshTransport: [DEBUG] Command to be executed: cd '/users/greschd' && sacct --format=AllocCPUS,Account,AssocID,AveCPU,AvePages,AveRSS,AveVMSize,Cluster,Comment,CPUTime,CPUTimeRAW,DerivedExitCode,Elapsed,Eligible,End,ExitCode,GID,Group,JobID,JobName,MaxRSS,MaxRSSNode,MaxRSSTask,MaxVMSize,MaxVMSizeNode,MaxVMSizeTask,MinCPU,MinCPUNode,MinCPUTask,NCPUS,NNodes,NodeList,NTasks,Priority,Partition,QOSRAW,ReqCPUS,Reserved,ResvCPU,ResvCPURAW,Start,State,Submit,Suspended,SystemCPU,Timelimit,TotalCPU,UID,User,UserCPU --parsable --jobs=8697759
```

My suspicion is that there's another process which gets spawned, and that gets killed by the ``Ctrl-C`` because it's not protected by the ``signal`` capture but since it belongs to the same process group it also gets the signal.

**Comment by greschd** [comment]
Concerning the issue with the wrong class loader: I think that also still exists. Here's why:

- In ``AiiDAPersister.save_checkpoint``, ``aiida.work.class_loader.CLASS_LOADER`` is passed to ``Bundle``
- In ``Bundle``, ``utils.class_name`` is used to save the loader to the bundle
- When unbundling, ``utils.load_instance`` is used to get back the class loader

Now the problem is that ``aiida.work.class_loader.CLASS_LOADER`` is not a separate class, but just an instance of ``plumpy.class_loader.ClassLoader``. So the ``utils.class_name`` just returns that.

**Comment by muhrin** [comment]
@greschd @sphuber Thanks for looking into this.  

So, can I just check I understand the signal-ing issue?  Is the problem roughly that we're using the signal the 'gracefully' begin a shutdown ourselves and therefore we don't want any subprocess to react to it - while `paramiko` has a subprocess that is terminating itself on the `SIGHUP` we're using to tell the worker to start a shutdown?

Re: the class loader - I think you're right Dominik.  The other thing we could do is just make our class loader actually subclass the default one, avoiding having to serialise it.

**Comment by greschd** [comment]
Yes, that about sums it up. There are also some other parts of the code which create subprocesses (local transport, postgres commands), and they can just always be given a separate process group. It probably makes sense to note this down in the developer's documentation. If you want I can add this to my existing PR.

**Comment by muhrin** [comment]
That'd be great.  It's a bit annoying that there's not a more general solution to this...

**Comment by greschd** [comment]
Where in the developer's doc should I put that? Did you plan on making a separate section on how the daemon works?

**Comment by greschd** [comment]
I created a new issue #1345 for the class loader problem, so that we can separate the two discussions.
